# WARNING: the artifactId below is hardcoded inside this project
# Dockerfile.  You must update the Dockerfile if you change this.
artifactId=azure-nosql
group=com.rubensgomes
description=Spring Boot demo integrating Azure Cosmos DB (NoSQL API)
title=Azure Cosmos DB Demo
mainClass=com.rubensgomes.azure.nosql.App

# version must end in SNAPSHOT for release plugin to work due to bug reported at:
# https://stackoverflow.com/questions/79675543/gradle-release-plugin-not-merging-main-to-release
version=0.0.1-SNAPSHOT

